// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


function fizzbuzz(x) {
  if (x % 3 === 0 && x % 5 === 0) {
    console.log("fizzbuzz");
    return /* () */0;
  } else if (x % 3) {
    if (x % 5) {
      console.log(x);
      return /* () */0;
    } else {
      console.log("buzz");
      return /* () */0;
    }
  } else {
    console.log("fizz");
    return /* () */0;
  }
}

for(var x = 1; x <= 100; ++x){
  fizzbuzz(x);
}

exports.fizzbuzz = fizzbuzz;
/*  Not a pure module */
