// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function factorial(x) {
  var match = +(x <= 2);
  if (match !== 0) {
    return x;
  } else {
    return Caml_int32.imul(x, factorial(x - 1 | 0));
  }
}

console.log("factorial of 5 = " + Pervasives.string_of_int(factorial(5)));

function fib(x) {
  if (x <= 2) {
    return 1;
  } else {
    return fib(x - 1 | 0) + fib(x - 2 | 0) | 0;
  }
}

console.log("5th element of fibonacci = " + Pervasives.string_of_int(fib(10)));

exports.factorial = factorial;
exports.fib = fib;
/*  Not a pure module */
